### ISSUE TITLE
Make script name, description and description page localizable

### ISSUE THREAD

**Issue by t-fr** [OpenUserJs/OpenUserJS.org#716] opened 2015-08-22 22:55 UTC
On Greasy Fork, script authors are able to [localize the script name and description](https://greasyfork.org/help/meta-keys). Also, the author can use separate description pages for each language. Only the name, description and description page in the selected language is shown.

Please add this functionality also on OpenUserJS.org.

But I think before realizing this issue the site UI needs to be translated (see issue #18).

**Comment by Martii** [comment] 2015-08-22 22:58
Duplicate of #285 and of course your forementioned #18

**Closed by Martii** 2015-08-22 22:58 UTC
Labels: duplicate
