### ISSUE TITLE
Rating Bar Near Invisible Negative Number

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#640] opened 2015-06-10 15:10 UTC
For the first time I noticed a negative number beside the number of votes on the script's page progress bar (div.progress-bar-danger). A more visible colour would be preferable if it is not meant to be hidden. 

Also, the negative number makes little sense to the end-user as it isn't infinitive how it is calculated using flags/down votes. 

Unrelated suggestion: an easier way to tell if a script is flagged in authors page and even in listing. Maybe a little flag above the progress bar in the listing pages.

**Comment by Martii** [comment] 2015-06-10 15:22
> Unrelated suggestion: an easier way to tell if a script is flagged in authors page and even in listing. Maybe a little flag above the progress bar in the listing pages. 

Duplicate of #499 

>  negative number beside the number of votes on the script's page progress bar

Intended behavior at #288

**Closed by Martii** 2015-06-10 15:22 UTC

**Comment by sizzlemctwizzle** [comment] 2015-06-10 15:23
You're right. A negative rating is barely noticeable. As for not showing
flags, that is done to prevent hivemind behavior (you flag a script just
because it is already flagged). Any flagged script shows up in moderators
dashboard for removal. Congrats, you are now a moderator. Just remember to
check to see if there are any open issues on a flagged script before
removing (you should always investigate why the script is flagged). @Martii
likes to give some authors warnings before removing.

**Comment by Martii** [comment] 2015-06-10 15:26
> @Martii likes to give some authors warnings before removing.

Depends on the severity... obfuscation is absolutely immediate. The TOS is what I try follow since it is a combination of stuff even before I came along. :)

**Comment by sizzlemctwizzle** [comment] 2015-06-10 15:33
Maybe we should put some of those policies on our new script page
(/user/add/scripts)? There's a little room under  the "New Script" section.

**Comment by Martii** [comment] 2015-06-10 15:38
> Maybe we should put some of those policies on our new script page

Terms of Service is linked on every page already and is necessary to find at any entry point on the site... so that would be extremely redundant and duplication is unnecessary for existing compliance with legal... speaking of I have a hearing to get to. bbl.

**Comment by TimidScript** [comment] 2015-06-10 16:20
Thank you for the moderation rights, but I doubt I fulfil the role well. I think it is best to remove the rank. ^_^

Just out of interest, by looking at the mod actions, a few questions have risen:

1) If a script is flagged because it has become malicious but is not over the threshold, what is the point of flagging. Isn't flagging meant to get mods attention. I just tested this on one of my scripts, I flagged it but because it has a lot of up votes it is not in the moderators flag list. If one updates a popular script and inserts hidden malicious code, it will take a few flags before the script shows up on the moderators list, in the meantime it keeps on infecting. 

2) How does one remove the flagged script from the list, if it is flagged by another? 

3) More importantly how does one remove a flagged user from the list. There are a few flagged users that have no ill comments on the forum and no scripts but flagged for unknown reason.

**Comment by sizzlemctwizzle** [comment] 2015-06-10 20:14
>  I think it is best to remove the rank.

Done, at your request.

> but is not over the threshold

Currently the threshold is at one flag, but upvotes negate flags to protect popular scripts from haters.

>  If one updates a popular script and inserts hidden malicious code, it will take a few flags before the script shows up on the moderators list

This is why we have admin. It is the job of admin to catch things that may fall between the cracks. I still need to show absolute number of flags in the script listings for admins. #641

> How does one remove the flagged script from the list, if it is flagged by another?

It doesn't matter who flagged it. There is "Mod tools" section that includes a remove button. We force you to actually go to the script page to remove it. That way maybe you won't blindly remove scripts.

>  More importantly how does one remove a flagged user from the list. There are a few flagged users that have no ill comments on the forum and no scripts but flagged for unknown reason.

We still don't have a solution for the case that something is improperly flagged. We might add a button that sets `user.flagged = false` #642. If they get flagged again, they'll show back up on the moderator dashboard. Admins likely need a way to see who flagged something to remove users that flag things for no conceivable reason. #643

**Comment by Martii** [comment] 2015-06-10 21:12
> We still don't have a solution for the case that something is improperly flagged.

Currently I manually inspect the items that show up and either negate the flag or assume the role of the flagger. I know this isn't currently the best approach but until the listing of who did what is available in the UI. e.g. a master flag that should be available to at the very least admins and up to ensure that things are in order and override the user/author flags. Part of #262 to improve this procedure.

There are also a few that are being "watched" from the admin side that I do on the user themselves in case they doing an instance of spam or accidental stuff *(a current example of a weird reply [here](https://openuserjs.org/scripts/Nilsnsn/2minmanXtended/issues/Skript_funktioniert_nicht_--_Browser_und_Betriebssysteme#comment-14dd329097e)... but I know Sebastian probably didn't mean to do this... so I haven't flagged that author.)*... e.g. if they spam again and are flagged by me they are bye bye for violation of the TOS. In other words I usually give one chance depending on the severity.

**Comment by TimidScript** [comment] 2015-06-10 21:26
Thank you both for detailed the info. 

> This is why we have admin. It is the job of admin to catch things that may fall between the cracks. I still need to show absolute number of flags in the script listings for admins. #641

This is a bit extreme for admin, isn't it? There are thousands of scripts and it is too much for mods. As the site gets more popular, the numbers will be too much. 

> We force you to actually go to the script page to remove it. That way maybe you won't blindly remove scripts.

Couldn't find that option when I had the privilege. 

> There are also a few that are being "watched" from the admin side that I do on the user themselves in case they doing an instance of spam or accidental stuff

Accidental posting (something I am guilty of) occurs sometimes, and without edit makes it a bit of a nuisance. :)

**Comment by Martii** [comment] 2015-06-10 21:31
> This is a bit extreme for admin, isn't it?

It's part of the job description. The filtering system and proposals from the new issues that @sizzlemctwizzle has created should be sufficient. This is all a team effort including users and author contributions. Eventually my proactive nature will be subdued by those issue completions and I won't need to be as persistent and be able to turn it over to the community for evaluation. I will still look for obfuscated code though as that is considered severe in my book unless otherwise directed by the establishing owner, sizzle... in which the TOS needs to be amended.

> without edit makes it a bit of a nuisance

Patience please... until then use the preview before commenting. ;)

**Comment by sizzlemctwizzle** [comment] 2015-06-10 21:38
We can have as many mods as we want. They are cheap. The moderation system
was design so that mod privileges have a low risk of abuse. That's why
there's a flag threshold in the first place.

Mods don't have to be completely trusted. We can scale the number of mods
with the site. We can make mods without their permission. Just put a one
time notification at the top of the page for them and they can decide when
and if they want to help out.

Admins on the other hand, have far greater privileges. They must be
trusted. There will only ever be a few.
