### ISSUE TITLE
Suggestion  - Way to Change Name and Keep Stats

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#1007] opened 2016-05-22 09:44 UTC
Please provide a way for us to change the name of the script and still keep the favoured users (not yet implemented), up votes and count. This is how both GF and defunct USO worked.

**Comment by Martii** [comment] 2016-05-22 15:24
Duplicate of #266

**Closed by Martii** 2016-05-22 15:24 UTC
