### ISSUE TITLE
Reply covers the line of bottom post

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#520] opened 2015-01-11 22:37 UTC
When you reply on a long thread, the last line from the bottom post gets hidden.

![092](https://cloud.githubusercontent.com/assets/8114076/5697186/118349ba-99e2-11e4-91e7-d3994c0b2c24.png)

**Comment by jerone** [comment] 2015-01-11 23:01
Probably caused by https://github.com/OpenUserJs/OpenUserJS.org/pull/477. 
Reply-box could be a bit less high.

**Comment by Martii** [comment] 2015-01-12 20:40
Confirmed that it is a bug and related to #477.

See also:
* [documentation for bootstrap-markdown](http://www.codingdrama.com/bootstrap-markdown/) under Usage section header

I wasn't able to get these `data-*` attributes to work either in the views nor the jQuery script popup. Since this is marked as sooner if no one works on this soon I am more inclined to revert #477 since that was a minor inconvenience for visual display whereas this is more of a major inconvenience for replying to discussions.

**Comment by jerone** [comment] 2015-01-12 20:47
Or set the height back on only pages where it has a reply box.

**Comment by Martii** [comment] 2015-01-12 20:49
Tried that on the `body` and the footer had a bunch of space below it. Similar issue with Opera Presto and not supporting `calc` and `vh` units.

**Comment by jerone** [comment] 2015-01-12 21:04
Increasing the [height on the `#show-reply-form-when-visible`](https://github.com/OpenUserJs/OpenUserJS.org/blob/6138676292428654f1b62d3aa913fae1ba446cf0/views/pages/scriptIssuePage.html#L9) is sufficient.

**Comment by Martii** [comment] 2015-01-12 21:14
If we ever add any sidebar then #477 will crop up at the tail end of the page as it does now with this setting by increasing the space between the footer and the `div.container-fluid`.

**Comment by Martii** [comment] 2015-01-12 21:24
Fails at http://localhost:8080/discuss/520_Testing with `#show-reply-form-when-visible { height: 300px; }` *(picked a random big value along with some others)*

**Comment by Martii** [comment] 2015-01-12 21:30
Depending on the content it will cover the pagination e.g. creep upwards and potentially cause the same issue... will have to retry with #477 removed and see what it does.

**Comment by Martii** [comment] 2015-01-12 21:37
> will have to retry with #477 removed and see what it does.

With that PR removed it 100% consistently shows the top edge to be right below number 1 pagination element. This isn't true with `#show-reply-form-when-visible { height: 200px; }` where it is creeping all over the place.

**Comment by jerone** [comment] 2015-01-12 21:48
This did the trick at my end:
```
#show-reply-form-when-visible {
    height: 230px;
}
```

**Comment by Martii** [comment] 2015-01-12 22:13
That makes it more difficult to quickly measure if it's consistent or not. I've only gotten the creeping a few times but aligning to a known rendered baseline would help pinpoint steps to reproduce. This still affects #477 by putting the gap below instead of between columns. Let me do some finite pixel management and I'll get the exact value here and we can all do some "screenies" to compare.

**Comment by Martii** [comment] 2015-01-12 22:57
Okay so here's what I've got on dev for screenies:

* #477 Revert ![issue-520with477revertclipped](https://cloud.githubusercontent.com/assets/114709/5712883/59541256-9a73-11e4-9682-dc7092c4f5bc.png)
* #527 applied 
![issue-520with200pxclipped](https://cloud.githubusercontent.com/assets/114709/5712829/fd19316a-9a72-11e4-95ff-8c913f82462a.png)

... all in `Mozilla/5.0 (X11; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0`

@TimidScript I would appreciate it too if you would keep your eyes out for any derivations on the spacing and put up a "screenie"... I'll do the same and anyone else who is willing to participate. The tracking upstream label is on here because this may not be closed yet.

**Comment by Martii** [comment] 2015-01-14 06:18
I've visited just about every discussion both on dev and pro and this appears to be fixed with help from @jerone and the jQuery/CSS3 listeners. Closing as fixered. If it reappears reopen. Thanks for the help. :)

**Closed by Martii** 2015-01-14 06:18 UTC
Labels: bug, sooner, tracking upstream, UI
