### ISSUE TITLE
Open Issues in Profile Page

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#853] opened 2015-12-17 13:00 UTC
Ability to see open issues you have created in personal profile page. This will also encourage users to close them when they are resolved.

**Comment by Martii** [comment] 2015-12-18 01:42
Partial duplicate of #500 and root of #242.

I understand what you are looking for... when the site gets to that point I'll review all of these issues whether opened or closed. Thanks.

**Closed by Martii** 2015-12-18 01:42 UTC
