### ISSUE TITLE
Email address as user name, no way to change or leave the site

### ISSUE THREAD

**Issue by fi5er** [OpenUserJs/OpenUserJS.org#886] opened 2016-02-04 02:22 UTC
This is almost certainly a duplicate, but seeing that previous issues got closed when one person's problem was solved... here it is again. I just signed up for OUJS using a Google account, and the email address connected to that account was automatically used as my user name. Now I'm apparently stuck with that, since there is no way of changing the displayed name or leaving the site.

I did not see a "huge caution box" (or maybe it just wasn't huge enough for me to notice it). If I had known this would be an issue, I'd never have registered. If you can't fix this generally for some reason, please at least remove the "gmail.com" part from my user name.

I'm trying to avoid linking different sites with my identity for all eternity, including GitHub, so I'm not writing my user name in this issue; I'm the author of the "Sort Hacker News" script, that should identify me uniquely (at the moment). If you need to confirm this... you have my email address, obviously :)

Thank you.

**Comment by Martii** [comment] 2016-02-04 03:44
> This is almost certainly a duplicate

This is definitely duplicated...#359 and #233 

> I just signed up for OUJS using a Google account, and the email address connected to that account was automatically used as my user name.

I am going to need a little more proof of this... my secondary moderation account is Google base authentication and I had zero issues signing up with a custom name that I chose.

> Now I'm apparently stuck with that... please at least remove the "gmail.com" part from my user name.

If you email me or @sizzlemctwizzle directly **with that google email address** and it validates through all email services *(which takes more effort and time to confirm)*... see the DMCA link at the bottom of OUJS for his and mine is on [*node*s author list](https://github.com/nodejs/node/blob/435d571f225aeffe683035f4f6b7f4a5ef0d1f23/AUTHORS#L833) ... then one of us can remove the extension that you put in... **a preferred alternative** is to add your GH user authentication to your account on OUJS at https://openuserjs.org/user/preferences which will immediately validate your identity and let me process your request here.

> I did not see a "huge caution box" (or maybe it just wasn't huge enough for me to notice it).

It's huge...

![spotlightednewuserregistrationofcurrentoujs](https://cloud.githubusercontent.com/assets/114709/12805165/640da0d0-cab6-11e5-8419-31dc27c81b7c.png "For those needing extra clarity")


If you decide this is too much effort for you then you are out of luck on this request... closing as duplicates... but I still see any comments that you may add.

**Closed by Martii** 2016-02-04 03:44 UTC

**Comment by Martii** [comment] 2016-02-04 04:47
@fi5er 
Send me an email direct from gmail via the web interface... your third party SMTP has already failed validation because it's not a true gmail send... if you add the GH account I can always remove it from OUJS... that's why it's quicker and confirmed immediately.

**Comment by fi5er** [comment] 2016-02-04 04:58
OK. I have sent another email, directly from the web interface. I hope this meets your requirements now.

**Comment by Martii** [comment] 2016-02-04 05:06
Passed gmail web UI validation ... 

> please at least remove the "gmail.com" part from my user name.

It is now gone... I had to delete your script as those have references to your old username as well and take way too much time to manually fix... please reupload it at your convenience.

**Comment by fi5er** [comment] 2016-02-04 05:17
Thank you. Nevermind about the script - I'm not sure I want to contribute to a site that won't let me leave.

**Comment by Martii** [comment] 2016-02-04 05:21
As I just commented you may eventually resign when I get to that... but the bad apples have to be addressed as well as those who make mistakes like you've done here.
