### ISSUE TITLE
Fetch info from TL;DR legal and show license information.

### ISSUE THREAD

**Issue by KOLANICH** [OpenUserJs/OpenUserJS.org#614] opened 2015-03-31 19:12 UTC
https://tldrlegal.com/api/license/ - licenses list
https://tldrlegal.com/api/license/<license ID> - info about license

**Comment by Martii** [comment] 2015-03-31 19:14
Please don't use "TL;DR" which from my experience is "Too long didn't read".

As far the issue... what do you mean?

**Comment by Martii** [comment] 2015-03-31 19:16
If I'm understanding this issue correctly it a dupe of #438

**Comment by Martii** [comment] 2015-03-31 19:31
https://tldrlegal.com/ is alpha and non-standardized especially in .user.js. Closing as invalid and won't fix since it's a bit vague on the issue with duplication.

**Closed by Martii** 2015-03-31 19:31 UTC
Labels: duplicate

**Comment by KOLANICH** [comment] 2015-04-01 07:46
>If I'm understanding this issue correctly it is a dupe of #438
Not exactly. It is a database of brief contents of every license that can be visualised as a set of icons and is machine readable. Have you opened the links and tried to use the site?
I suggest to
1 daily fetch the db from there
2 visualise it : place after license name some info about it as a set of icons on colorful backgrounds.

**Comment by Dexmaster** [comment] 2015-04-01 08:40
1 I don't see the full [List of software licenses](http://en.wikipedia.org/wiki/List_of_software_licenses) there
2 where is [WTFPL](http://en.wikipedia.org/wiki/WTFPL) I like that one (even so I know that [MIT](http://en.wikipedia.org/wiki/MIT_License) is better, i still like WTFPL name more), and their [documentation is not public yet](https://tldrlegal.com/developers) (developer API). So as a result what we get from their API list of hash codes and non-standardized names? (where are texts, links and stuff like that?)
3 it's 1st of April don't be gloomy about 2

**Comment by Martii** [comment] 2015-04-01 19:51
@KOLANICH 
I've seen that site before and yes you don't need to ask owners that sort of question if it's been examined.

The largest issue I see is that it is eye candy that can be contained within the user content area of each script by the script authors not OUJS itself. It also doesn't encompass MIT custom licensing so the won't fix stands from here... licensing isn't always "canned" documents. If we end up linking somewhere with a standardized format from #438 it most likely will be [OSI](http://opensource.org/) and possibly adding node related [spdx identifiers](https://spdx.org/licenses/).

Making things extremely verbose is not always the best idea especially from the OUJS standpoint... Feel free to use your user content area.

@Dexmaster 
WTFPL isn't OSI approved... I understand the Public Domain gifts very well, and I've done my share in the past few decades, but publishing to OUJS is prohibited with that type of non-OSI licensing in the TOS.

**Comment by KOLANICH** [comment] 2015-04-01 21:29
O.K.
