### ISSUE TITLE
Payload too large

### ISSUE THREAD

**Issue by trumpeta** [OpenUserJS/OpenUserJS.org#1823] opened 2021-07-07 18:54 UTC
**What happened?**

I get Payload too large server response when trying to update my script

**What did you expect to happen?**

see below

**What the problem might be**

My script has grown through the time and since certain version I get these responses. Probably there's a size limit.
Please increase the limit so that the site would be able to absorb larger projects.

**Comment by Martii** [comment] 2021-07-07 20:26
Duplicate of #793

**Closed by Martii** 2021-07-07 20:26 UTC
Labels: bug
