### ISSUE TITLE
 Login is prompted all the time : 429 Too many requests. Please retry after approximately 86460 seconds. 

### ISSUE THREAD

**Issue by cyrus123456** [OpenUserJS/OpenUserJS.org#2029] opened 2023-12-17 11:58 UTC
### What happened?

https://openuserjs.org/auth/
![image](https://github.com/OpenUserJS/OpenUserJS.org/assets/73327722/963cffe2-9fcc-4c97-93c3-c50f8587eb39)

### What did you expect to happen?

![image](https://github.com/OpenUserJS/OpenUserJS.org/assets/73327722/ab64ec86-5e2b-4e11-a82b-113f7b253542)

### What the problem might be?

![image](https://github.com/OpenUserJS/OpenUserJS.org/assets/73327722/7fba126d-e1bd-43be-afad-d3f0c2945409)

**Comment by Martii** [comment] 2023-12-17 17:31
Wait the specified number of seconds *(approximately 1 day)* and then you may log in. All new users have this feature while they are on probation i.e. "cool down" period as some call it.

Duplicate of #1928

**Closed by Martii** 2023-12-17 17:31 UTC
Labels: intended behavior
