### ISSUE TITLE
Import Scripts from GitHub

### ISSUE THREAD

**Issue by Mottie** [OpenUserJs/OpenUserJS.org#1146] opened 2017-06-21 11:46 UTC
I have two accounts on OpenUserJS. One personal and one organizational.

I created the organizational account after my personal, and now when I want to update a userscript - since auto-updating isn't working - using the "Import Script from GitHub" always lands me on my personal GitHub account even though I am logged into the organization account:

![](https://user-images.githubusercontent.com/136959/27382426-957ba504-564c-11e7-8e27-9b0d8ef2b314.gif)

I know I can get around this by adding `?user={GitHub-login}` to the url, but the whole process of updating userscripts is already difficult.

**Comment by Martii** [comment] 2017-06-22 03:56
Duplicate of #231

**Closed by Martii** 2017-06-22 03:56 UTC
Labels: duplicate
