### ISSUE TITLE
[i18n] Localization

### ISSUE THREAD

**Issue by GreenLunar** [OpenUserJs/OpenUserJS.org#982] opened 2016-04-15 14:16 UTC
Make OUJS subjected to localization.

I would delightfully provide a translation of OUJS in my language.

**Comment by Martii** [comment] 2016-04-15 17:44
Duplicate of #18

**Comment by Martii** [comment] 2016-04-15 17:45
> I would delightfully provide a translation of OUJS in my language.

That would be nice when the time comes... but there are other issues in the queue to fix first. Thanks.

**Closed by Martii** 2016-04-15 17:44 UTC
Labels: duplicate

**Comment by GreenLunar** [comment] 2016-04-15 18:52
Thank you.
